steps:
# Clone CLV repo
- name: 'gcr.io/cloud-builders/git'
  args:
  - clone
  - --branch
  - deploy-kfp
  - --depth
  - '1'
  - --verbose
  - https://github.com/${_CLV_REPO}
  - clv

# Build the image for custom build steps 
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'kfp-builder', '.']
  dir: 'clv/deploy/kfp-builder'

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['container', 'clusters', 'get-credentials', '$_CLUSTER_NAME', '--zone', '$_ZONE']


#- name: 'gcr.io/cloud-builders/gcloud'
#  entrypoint: '/bin/bash'
#  args:
#  - '-c'
#  - |
#    cat ~/.kube/config 
#    kubectl get nodes
#
#- name: 'gcr.io/cloud-builders/gcloud'
#  entrypoint: '/bin/bash'
#  args:
#  - '-c'
#  - |
#    cp ~/.kube/config .
#
  
- name: 'kfp-builder'
  args:
  - '-c'
  - |
    python kfp-cli.py create_experiment experiment4
  dir: 'clv/kfp-cli'

