steps:

# Clone CLV repo
- name: 'gcr.io/cloud-builders/git'
  args:
  - clone
  - --depth
  - '1'
  - --verbose
  - https://github.com/${_CLV_REPO}
  - clv_pipelines

# Build a base image for lightweight components
- name: 'gcr.io/cloud-builders/docker' 
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/${_BASE_IMAGE}', '.'] 
  dir: 'clv_pipelines/components/lightweight_components_base_image'

# Build the AutoML Tables component image
- name: 'gcr.io/cloud-builders/docker' 
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/${_AUTOML_TABLES_IMAGE}', '.'] 
  dir: 'clv_pipelines/components/automl_tables'

# Create a custom builder with the KFP compiler
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'kfp-compiler', '.']
  dir: 'clv_pipelines/cloud-build/kfp-compiler-builder'

# Create AutoML Tables component specs 
- name: 'kfp-compiler'
  entrypoint: 'python'
  args: ['generate_component_specs.py', '.', 'gcr.io/$PROJECT_ID/$_AUTOML_TABLES_IMAGE']
  dir: 'clv_pipelines/components/automl_tables/specs'

# Compile pipelines 
- name: 'kfp-compiler'
  args: ['compile_pipelines.sh']
  dir: 'clv_pipelines/pipelines'

# Compile pipelines 
- name: 'kfp-compiler'
  args: ['-c', 'ls -la']
  dir: 'clv_pipelines/pipelines'

#images: ['gcr.io/$PROJECT_ID/${_BASE_IMAGE}', 'gcr.io/$PROJECT_ID/${_AUTOML_TABLES_IMAGE}']