steps:

# Clone CLV repo
- name: 'gcr.io/cloud-builders/git'
  args:
  - clone
  - --depth
  - '1'
  - --verbose
  - https://github.com/${_CLV_REPO}
  - clv_pipelines

# Build a base image for lightweight components
- name: 'gcr.io/cloud-builders/docker' 
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/$_BASE_IMAGE', '.'] 
  dir: 'clv_pipelines/components/lightweight_components_base_image'

# Build the AutoML Tables component image
- name:  'gcr.io/cloud-builders/docker' 
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/$_AUTOML_TABLES_IMAGE', '.'] 
  dir: 'clv_pipelines/components/automl_tables'

# Create a custom builder with the KFP compiler
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'kfp-compiler', '.']
  dir: 'clv_pipelines/cloud-build/kfp-compiler-builder'

# Create AutoML Tables component specs 
- name: 'kfp-compiler'
  entrypoint: 'python'
  args: ['generate_component_specs.py', 'gcr.io/$PROJECT_ID/$_AUTOML_TABLES_IMAGE']
  dir: 'clv_pipelines/components/automl_tables'

# Configure KFP compilation 
- name: 'kfp-compiler'
  entrypoint: 'python'
  args: ['configure_compiler_directives.py', '--url_search_prefixes', '$_URL_SEARCH_PREFIXES']
  dir: 'clv_pipelines/pipelines'

# Compile the pipelines 
- name: 'kfp-compiler'
  args:
  - '-c'
  - |
    dsl-compile --py  src/train_pipeline.py --output $_TRAIN_PIPELINE --disable-type-check
  dir: 'clv_pipelines/pipelines'

- name: 'kfp-compiler'
  args:
  - '-c'
  - |
    dsl-compile --py  src/batch_predict_pipeline.py --output $_PREDICT_PIPELINE --disable-type-check
  dir: 'clv_pipelines/pipelines'

# Deploy the compiled pipelines to GCS
- name: 'gcr.io/cloud-builders/gsutil'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    gsutil mb -p $PROJECT_ID gs://$_BUCKET_NAME || exit 0

- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', '*.tar.gz', 'gs://$_BUCKET_NAME']
  dir: 'clv_pipelines/pipelines'

# Deploy the SQL query template
- name: 'gcr.io/cloud-builders/gsutil' 
  args: ['cp', 'src/query_template_sql.jinja', 'gs://$_BUCKET_NAME']
  dir: 'clv_pipelines/pipelines'

# Push component images
images: ['gcr.io/$PROJECT_ID/${_BASE_IMAGE}', 'gcr.io/$PROJECT_ID/${_AUTOML_TABLES_IMAGE}']