steps:
# Clone CLV repo
- name: 'gcr.io/cloud-builders/git'
  args:
  - clone
  - --branch
  - deploy-kfp
  - --depth
  - '1'
  - --verbose
  - https://github.com/${_CLV_REPO}
  - clv

 # Create the image for custom build steps 
# - name: 'gcr.io/cloud-builders/docker'
#  args: ['build', '-t', 'kfp-helper', '.']
#  dir: 'clv/deploy/kfp-helper'

- name: 'gcr.io/jktest4/kfp-helper'
  args:
  - '-c'
  - |
    echo "Hello"
    gcloud container clusters get-credentials ${_CLUSTER} --zone ${_ZONE}
    ps -a
    kubectl port-forward svc/ml-pipeline -n kubeflow 8082:8888 & 
    #python3 kfp-cli.py create_experiment exp3 --host http://localhost:8082
    ps -a
  dir: 'clv/kfp-cli'




